### ISSUE TITLE
Samples are failing at runsnp step of AMR++

### ISSUE THREAD

**Issue by LLansing** [Microbial-Ecology-Group/AMRplusplus#10]
I am running AMR++ pipeline on 177 paired samples. The entirety of the run is successful except that 18 samples fail the runsnp step of the pipeline with the following error in the nextflow output:

[c8/b4aa4e] NOTE: Process STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (SRR13495884) terminated with an error exit status (1) -- Error is ignored

and in the .command.err files, they all end with a similar cut error:

...
++ awk -v RS=, '/SRR13495950/{print NR; exit}' AMR_analytic_matrix.csv
+ cut -d , -f AMR_analytic_matrix.csv
cut: invalid byte, character or field list
Try 'cut --help' for more information.
++ kill 60302

This results in those 18 samples missing from the SNPconfirmed_AMR_analytic_matrix.csv file.

A previous run of the pipeline with the same data had 25 samples with this error, and only 3 erroneous samples in common between the two runs. This makes it seem like the error is somewhat random.

([Cross-posted from AMRplusplus_SNP](https://github.com/Isabella136/AmrPlusPlus_SNP/issues/21))

**Comment by Isabella136** [comment]
May be connected to #9 since as of now both issues always occur together

**Comment by EnriqueDoster** [comment]
@LLansing, sorry for the delay but we just pushed updates to AMR++ (v3.0.1) and the [AmrPlusPlus_SNP](https://github.com/Isabella136/AmrPlusPlus_SNP) software which should solve the issues you were running into. Please try the latest version of AMR++ and let us know if you run into any further issues.
