### ISSUE TITLE
Error executing process > 'FAST_AMRplusplus:FASTQ_TRIM_WF:runqc (S1_R1)

### ISSUE THREAD

**Issue by priscillaisaac98** [Microbial-Ecology-Group/AMRplusplus#13]
Run this command: nextflow run main_AMR++.nf --help

But it shows this error;
Error executing process > 'FAST_AMRplusplus:FASTQ_TRIM_WF:runqc (S3_test)'

Caused by:
  No such variable: TRIMMOMATIC -- Check script 'subworkflows/../modules/Trimming/trimmomatic.nf' at line: 43

Source block:
  """
       ${TRIMMOMATIC} \
        PE \
        -threads ${threads} \
        ${reads[0]} ${reads[1]} ${sample_id}.1P.fastq.gz ${sample_id}.1U.fastq.gz ${sample_id}.2P.fastq.gz ${sample_id}.2U.fastq.gz \
        ILLUMINACLIP:${adapters}:2:30:10:3:TRUE \
        LEADING:${leading} \
        TRAILING:${trailing} \
        SLIDINGWINDOW:${slidingwindow} \
        MINLEN:${minlen} \
        2> ${sample_id}.trimmomatic.stats.log
        
      """

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

Anyone can help me out with this?

**Comment by EnriqueDoster** [comment]
Hi @priscillaisaac98, thank you for reporting this. We found that we would sometimes have issues with the parsing of environmental variables and have now updated how this is handled. Please try the updated AMR++ (v3.0.1) code and let us know if you run into any issues. Thank you!

**Comment by priscillaisaac98** [comment]
Hi,

I tried the latest AMR++(v3.0.1) code and still got an error but this time
with a different error.
It showed :Error executing process >
'FAST_AMRplusplus:FASTQ_RESISTOME_WF:runrarefaction (Virome1)'; Caused by:
Process `FAST_AMRplusplus:FASTQ_RESISTOME_WF:runrarefaction (Virome1)`
terminated with an error exit status (1). Is there any idea how I can solve
this? Thank you.

Regards,
Priscilla

[image: image.png]
[image: image.png]
