### ISSUE TITLE
Why is chr21 chosen for human read removal?

### ISSUE THREAD

**Issue by tjdallman** [Microbial-Ecology-Group/AMRplusplus#14]
Hello,
I am wondering why chr21 is chosen for human read removal by default and not the whole genome e.g. GRCh38?
Many thanks,
Tim

**Comment by EnriqueDoster** [comment]
Hi Tim,

Ch21 is only used as an example fasta file to avoid including larger files in the repository. I would recommend running AMR++ with the entire genome as you mentioned. 

Thanks!
