### ISSUE TITLE
pipeline demo crashes when parsing nextflow.config

### ISSUE THREAD

**Issue by asogg** [Microbial-Ecology-Group/AMRplusplus#15]
Hi,
i'm trying to use the AMR++ pipeline but it crashes when parsing nextflow.config here the error:

**nextflow run main_AMR++.nf -profile singularity --pipeline demo
N E X T F L O W  ~  version 22.10.6
Unable to parse config file: '/home/as/AMRplusplus/nextflow.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/ScriptB6DED1A25169A5D2CA887C49E3310682']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/ScriptB6DED1A25169A5D2CA887C49E3310682: 18: Unexpected input: '{' @ line 18, column 9.
     process {
             ^
  
  1 error**

any suggestion?
thanks
Alessio

**Comment by felipemachado85** [comment]
Hi, have you been able to come up with a solution? I'm getting the same error. 

Thanks!

Felipe

**Comment by asogg** [comment]
Hi Felipe,
unfortunately not at the moment, will see testing another nextflow version.
cheers
Alessio

**Comment by felipemachado85** [comment]
Hi Alessio,

Thanks for the reply. I've managed to get the pipeline running:
# After downloading the AMR++ repository, navigate into it and use the following command to create a conda environment.
# If you have mamba installed, change "conda" to "mamba" for quicker installations. 
conda env create -f envs/AMR++_env.yaml
# Now activate the conda environment
conda activate activate AMR++_env

This worked for the demo pipeline, at least. When I try with my reads it doesn't work properly, maybe you can give it a try with yours.

Good luck.

**Comment by asogg** [comment]
Hi felipe,
Thanks for the suggestion!, I'll test both ( demo and my data) . Will see if it works.
Cheers
Alessio

**Comment by EnriqueDoster** [comment]
Hello, 

Thank you @felipemachado85, we just updated AMR++ which should solve the first issue when running with `-profile singularity`. Basically, I was missing quotes around the container name so nextflow couldn't parse the file correctly. We've also updated the docs to recommend installation with conda, as Felipe recommended. You should be free to try either installation. I'm closing this comment as the error should have been fixed, but please let us know if you run into any further issues.

Thanks!
Enrique
