### ISSUE TITLE
Error when running AMR++(v3.0.1)

### ISSUE THREAD

**Issue by priscillaisaac98** [Microbial-Ecology-Group/AMRplusplus#19]
I tried the latest AMR++(v3.0.1) code and still got an error but this time
with a different error.
It showed :Error executing process >
'FAST_AMRplusplus:FASTQ_RESISTOME_WF:runrarefaction (Virome1)'; Caused by:
Process `FAST_AMRplusplus:FASTQ_RESISTOME_WF:runrarefaction (Virome1)`
terminated with an error exit status (1). Is there any idea how I can solve
this? Thank you.

**Comment by EnriqueDoster** [comment]
Hello @priscillaisaac98,

We'll need a bit more information to track this down. Can you please look in the ".nextflow.log" file which you can find in your AMR++ working directory?  You can attach it here in your next response, or try to follow these next steps on your own.

Look through the .nextflow.log file to find the "runrarefaction" process that is associated with Virome 1. This will have a working directory associated with this process. Check that directory for the ".command.log" file and let me know what you find. 

A few other questions. Did the rest of the pipeline steps work for this and other samples? Did you have rarefaction results for other samples?

Thanks!

**Comment by EnriqueDoster** [comment]
Closing this for now due to inactivity, but please try the latest code for AMR++ and let us know if you run into any issues. Thanks!
