### ISSUE TITLE
runsnp failing

### ISSUE THREAD

**Issue by LLansing** [Microbial-Ecology-Group/AMRplusplus#2]
Nextflow output shows this message for failed runsnp job:
``[2e/4888ce] NOTE: Process `STANDARD_AMRplusplus_wKraken:FASTQ_RESISTOME_WF:runsnp (NS.1508.003.IDT_i7_165---IDT_i5_165.COR05e_t2_M)\` terminated with an error exit status (1) -- Error is ignored``

and the `.command.err` file shows the following (with absolute paths censored by me after the fact):

> \+ nxf_launch
> \+ /bin/bash -uex /isilon/lacombe-rdc/users/tranlan/amrplusplus/AMRplusplus/work/2e/4888ce3a02f09dbe5aa8aba2b60194/.command.sh
> \+ python3 AmrPlusPlus_SNP/SNP_Verification.py -i NS.1508.003.IDT_i7_165---IDT_i5_165.COR05e_t2_M.amr.alignment.sam -o NS.1508.003.IDT_i7_165---IDT_i5_165.COR05e_t2_M_SNPs
> Traceback (most recent call last):
>   File "<absolute path>/AMRplusplus/work/2e/4888ce3a02f09dbe5aa8aba2b60194/AmrPlusPlus_SNP/SNP_Verification.py", line 110, in <module>
>     config['SOURCE_FILES']['SAM_INPUT'] = arg
>   File "<absolute path>/python-09679a002b117b56bcf8ad7be35338e2/lib/python3.9/configparser.py", line 963, in __getitem__
>     raise KeyError(key)
> KeyError: 'SOURCE_FILES'

[Fail location in AmrPlusPlus_SNP](https://github.com/Isabella136/AmrPlusPlus_SNP/blob/4dd3ab7599620bf88a7abb9efdab00d5376bdadf/SNP_Verification.py#L110)
My amateur suggestion is that the problem is the following:

- the `SNP_Verification.py` script is expecting to be ran from within the AmrPlusPlus_SNP directory, and as such tries to read the configFile 'config.ini' path with such an expectation. I suspect that the `runsnp` process calls the `SNP_Verification.py` script from a higher directory, based on [line 105 in resistome.nf](https://github.com/Microbial-Ecology-Group/AMRplusplus/blob/master/modules/Resistome/resistome.nf#L105)

If this is the cause of the problem, I'm not sure I can patch a solution myself and, if this is not the cause of the problem, I'm even more lost.

Thanks for your help

**Comment by EnriqueDoster** [comment]
Hi @LLansing ,

Thanks for reporting this and providing a useful suggestion! 
We had to make a few updates to make things work again due to the requirement from AmrPlusPlus_SNP that the command needs to be run within the main directory. We patched something together now that, while not the prettiest code, will work to get the SNP verification working. Please try pulling the latest updates to AMR++ and run your command, but now including the ```--snp Y``` flag. Let me know how that goes for you!

Best,
Enrique

**Comment by LLansing** [comment]
Thanks Enrique, I will be able to test it out next week

**Comment by LLansing** [comment]
SNP seems to have worked, although there is 1 of my samples missing. The missing sample is present in the `results/ResistomeCounts` as well as in the non-SNP `AMR_analytic_matrix.csv`

**Comment by LLansing** [comment]
I'm not sure if this is the same problem as the run I mentioned in the previous comment, but while running the pipeline again, I noticed 3 samples missing from the SNPconfirmed_AMR_analytic_matrix.csv. The 3 missing samples all failed during the run, showing the following message:

> [88/801dcb] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA02e_t2_M)` terminated with an error exit status (1) -- Error is ignored
[98/073afc] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA01e_t2_M)` terminated with an error exit status (1) -- Error is ignored
[5d/62f34d] NOTE: Process `STANDARD_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (CRA03u_t2_M)` terminated with an error exit status (1) -- Error is ignored

And each show a similar error in the `.command.err` files:

> \+ nxf_launch
\+ /bin/bash -uex <root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/.command.sh
\+ cp -r <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/config.ini <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/data <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/genes-issues.md <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/LICENSE <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/README.md <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification_Processes <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification.py <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/SNP_Verification_Tools <root path>/AMRplusplus/bin/AmrPlusPlus_SNP/usage.md .
\+ python3 SNP_Verification.py -c config.ini -a -i CRA02e_t2_M.alignment.sam -o CRA02e_t2_M_AMR_SNPs --count_matrix AMR_analytic_matrix.csv
Traceback (most recent call last):
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification.py", line 213, in <module>
    verify(read, gene, config)
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/__init__.py", line 26, in verify
    checkResult = NonsenseCheck(read, gene, mapOfInterest, seqOfInterest)   #Checks for nonsense previously found in literature and for new nonsense
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 9, in NonsenseCheck
    return verifyNonsense(read, gene, stopLocation, mapOfInterest)
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 37, in verifyNonsense
    findNonsenseLocation()
  File "<root path>/AMRplusplus/work/88/801dcb26e38a048e368ce895f969f3/SNP_Verification_Processes/NonsenseCheck.py", line 24, in findNonsenseLocation
    elif stopLocation < queryIndex:
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by LLansing** [comment]
Solved at [this issue](https://github.com/Isabella136/AmrPlusPlus_SNP/issues/19)
