### ISSUE TITLE
SNP broken in AMRplusplus

### ISSUE THREAD

**Issue by CarstenBaker** [Microbial-Ecology-Group/AMRplusplus#21]
Using the latest version of AMRplusplus (v3.0.2) and running this command for testing I get the following SNP errors:
```
nextflow run main_AMR++.nf -profile singularity --snp Y
```

Error
```
[aa/b2d3c7] NOTE: Process `FAST_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (S3_test)` terminated with an error exit status (1) -- Error is ignored
[9c/de97f2] NOTE: Process `FAST_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (S1_test)` terminated with an error exit status (1) -- Error is ignored
[da/82c3d1] NOTE: Process `FAST_AMRplusplus:FASTQ_RESISTOME_WF:runsnp (S2_test)` terminated with an error exit status (1) -- Error is ignored
```

Looking at the .command.err file I get

```
  File "SNP_Verification.py", line 275
    with (open(config['FULL_FILE_NAMES']['NTYPE_OUTPUT'], "w") as outputN,
                                                                ^
SyntaxError: invalid syntax
```

AmrPlusPlus_SNP has been updated to use >Python 3.9 but the singularity container for Amrplusplus still uses python 3.7.4 so will no longer work unless I am missing something obvious ?

Can you let me know if I am missing some guide for getting SNP working with AMRplusplus using singularity ?

**Comment by Isabella136** [comment]
@EnriqueDoster is it possible to update the singularity container so that it works with python 3.9, or do I need to make a version of AmrPlusPlus_SNP that is compatible with the current container?

**Comment by EnriqueDoster** [comment]
@CarstenBaker and @Isabella136 , 

Let me work on updating the singularity container ASAP! Sorry for the delay and thanks for bringing this to my attention!

In the meantime, you can also try the local [conda installation](https://github.com/Microbial-Ecology-Group/AMRplusplus/blob/master/docs/installation.md#installing-miniconda-without-sudo-permissions). I'll close this issue for now but count on the singularity container being updated by the end of the day. Thanks!
