### ISSUE TITLE
Two errors with v3.0.3

### ISSUE THREAD

**Issue by Isabella136** [Microbial-Ecology-Group/AMRplusplus#23]
So two errors appear when trying to run v3.0.3

The first is an issue with one of the process label specified in `fastqc.nf`:

    ERROR ~ Not a valid process label: Run multiqc -- Label must consist of alphanumeric characters or '_', must start with an alphabetic character and must end with an alphanumeric character

     -- Check script 'subworkflows/../modules/Fastqc/fastqc.nf' at line: 28 or see '.nextflow.log' file for more details

The second one is an issue with the input reads:

    Cannot find any reads matching: /blue/boucher/nbonin/AMRplusplusv303/AMRplusplus/data/raw/*_R{1,2}.fastq.gz

However, I just checked and all of the files are present in the `data/raw/` directory:

    ls data/raw/
    S1_test_R1.fastq.gz  S1_test_R2.fastq.gz  S2_test_R1.fastq.gz  S2_test_R2.fastq.gz  S3_test_R1.fastq.gz  S3_test_R2.fastq.gz

**Comment by felipemachado85** [comment]
Hi Isabela, 

It seems you have a problem with your initial input for multiqc. I would suggest looking over your fastq files to see if they're ok (try running them in a standalone QC like Fastqc to check if they're ok).

For the second problem, I would recommend creating a new folder containing your sequences inside the AMRplusplus folder (this raw/data folder contains files pertaining to the demo pipeline), so your path would be significantly reduced. I had the same problem and when it worked when I did this. 

I hope this could be of any help to you!

**Comment by Isabella136** [comment]
I'm actually using the demo fastq files, so I doubt that the issue comes from there.

The first issue comes from the "Run multiqc" label in the fastqc.nf file; nextflow doesn't seem to accept a label with a space character. 

I have yet to test v.3.0.4, but based on the code modifications, it should have fixed both errors.

**Comment by EnriqueDoster** [comment]
@Isabella136 and @feli , 

Yeah thanks for catching this, I was making little mistakes and incorrectly named a label for a process. Somehow this also causes the error to show that the test reads were not found. The latest code fixes this and it should work fine now. Thanks!
