### ISSUE TITLE
Parsing of nextflow.config crash

### ISSUE THREAD

**Issue by aghozlane** [Microbial-Ecology-Group/AMRplusplus#3]
Hello,

I can't use the conda install, but I guess I do have all dependencies already installed.
I am trying to use the profile singularity_slurm, but the demo crash when parsing nextflow.config with the following error:
```
$../nextflow run main_AMR++.nf -profile singularity_slurm --pipeline demo
Unable to parse config file: '/***/***/***/aghozlan/AMRplusplus/nextflow.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/ScriptC7B9CD1F2358AA28CEFA0230C7243C79']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/ScriptC7B9CD1F2358AA28CEFA0230C7243C79: 16: Unexpected input: '{' @ line 16, column 9.
     process {
```
I tried nextflow version 22.10.2.5832, nextflow version 20.10.0.5430. We have apptainer 1.0.3 instead of singularity.

Any idea ?

**Comment by EorgeKit** [comment]
### Issue #4

**Comment by EnriqueDoster** [comment]
Hello @aghozlane , could you please try running this again using the most recent AMR++ code and let us know how it goes?
I believe we fixed the issue with the nextflow.config file, but server settings can sometimes make working with singularity and slurm difficult.

**Comment by EnriqueDoster** [comment]
We are closing this issue as the latest updates to AMR++ v3.0.1 should address this error. Please let us know if you run into any further issues. Thank you!
